# SwiftLint Configuration for Momento
# This file defines linting rules for consistent Swift code style

# Paths to exclude from linting
excluded:
  - Momento.xcodeproj
  - MomentoTests
  - MomentoUITests
  - build
  - .build
  - Pods
  - Carthage

# Opt-in rules (not enabled by default)
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Disabled rules
disabled_rules:
  - trailing_whitespace # Can be annoying during development
  - todo # Allow TODO comments for now

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - URL
    - url
    - now
    - h
    - m
    - s

# Custom rules for Momento
custom_rules:
  momento_comment_style:
    name: "Momento Comment Style"
    regex: '\/\/\s*MARK:\s*-\s*[A-Z]'
    message: "Use MARK comments for code organization"
    severity: warning

# Warnings are treated as warnings (not errors)
warning_threshold: 100

# Reporter type
reporter: "xcode"

