default_platform(:ios)

platform :ios do
  desc "Setup Match certificates"
  lane :setup_match do
    api_key = app_store_connect_api_key(
      key_id: "ZPWYQC3TN3",
      issuer_id: "6555c846-269e-4790-96ec-2574330dc6ad",
      key_filepath: File.expand_path("~/Documents/AuthKey_ZPWYQC3TN3.p8")
    )

    match(
      type: "appstore",
      readonly: false,
      api_key: api_key
    )
  end


  desc "Build and upload to TestFlight"
  lane :beta do
    # Set up API Key authentication
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_API_KEY_PATH"]
    )

    # Increment build number
    increment_build_number(
      xcodeproj: "Momento.xcodeproj"
    )

    # Build the app (certificates already imported by GitHub Actions)
    build_app(
      scheme: "Momento",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.asad.Momento" => "449735c2-723c-49c0-b2d8-0c944e8ff714"
        }
      }
    )

    # Upload to TestFlight
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false
    )
  end
end
